name: wokwi_test
on: [push, workflow_dispatch]
jobs:
  wokwi_test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v6
        with:
          repository: TinyTapeout/tt-support-tools
          path: tt
          ref: tt10

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: |
          pip install -r test/requirements.txt
          pip install -r tt/requirements.txt

      - name: Fetch the truth table
        run: |
          ./tt/tt_tool.py --create-user-config
          test -f test/truthtable.md || {
            echo "::error::test/truthtable.md was not generated"
            exit 1
          }

      - name: Check for truth table existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "test/truthtable.md"

      - name: Run tests
        id: run_tests
        if: steps.check_files.outputs.files_exists == 'true'
        working-directory: test
        run: |
          make clean
          make
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep -q failure results.xml

      - name: Test Summary
        if: always() && steps.check_files.outputs.files_exists == 'true'
        uses: test-summary/action@v2.4
        with:
          paths: "test/results.xml"

      - name: upload vcd
        if: always() && steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@v7
        with:
          name: test-vcd
          if-no-files-found: ignore
          path: |
            test/*.vcd
            test/results.xml
